export const REDACTION_STATUS = {
	REDACTED: 'redacted',
	UNREDACTED: 'not_redacted',
	NO_REDACTION_REQUIRED: 'no_redaction_required'
};

export const AVSCAN_STATUS = {
	NOT_SCANNED: 'not_scanned',
	SCANNED: 'scanned',
	AFFECTED: 'affected'
};

export const ORIGIN = {
	CITIZEN: 'citizen',
	LPA: 'lpa',
	PINS: 'pins',
	OGD: 'ogd'
};

export const STAGE = {
	APPELLANTCASE: 'appellant-case',
	LPAQUESTIONNAIRE: 'lpa-questionnaire',
	APPEALDECISION: 'appeal-decision',
	COSTS: 'costs',
	INTERNAL: 'internal',
	STATEMENTS: 'statements',
	THIRDPARTYCOMMENTS: 'third-party-comments',
	FINALCOMMENTS: 'final-comments'
};

export const DOCTYPE = {
	APPELLANTCASECORRESPONDENCE: 'appellantCaseCorrespondence',
	APPELLANTCASEWITHDRAWAL: 'appellantCaseWithdrawalLetter',
	APPELLANTCOSTAPPLICATION: 'appellantCostsApplication',
	APPELLANTCOSTCORRESPONDENCE: 'appellantCostsCorrespondence',
	APPELLANTCOSTWITHDRAWAL: 'appellantCostsWithdrawal',
	APPELLANTSTATEMENT: 'appellantStatement',
	APPLICATIONDECISION: 'applicationDecisionLetter',
	CHANGEDDESCRIPTION: 'changedDescription',
	ORIGINALAPPLICATIONFORM: 'originalApplicationForm',
	WHONOTIFIED: 'whoNotified',
	CONSERVATIONMAP: 'conservationMap',
	LPACASECORRESPONDENCE: 'lpaCaseCorrespondence',
	LPACOSTAPPLICATION: 'lpaCostsApplication',
	LPACOSTCORRESPONDENCE: 'lpaCostsCorrespondence',
	LPACOSTWITHDRAWAL: 'lpaCostsWithdrawal',
	OTHERPARTYREPS: 'otherPartyRepresentations',
	PLANNINGOFFICERREPORT: 'planningOfficerReport',
	COSTDECISIONLETTER: 'costsDecisionLetter',
	CASEDECISIONLETTER: 'caseDecisionLetter',
	CROSSTEAMCORRESPONDENCE: 'crossTeamCorrespondence',
	INSPECTORCORRESPONDENCE: 'inspectorCorrespondence'
};

export const FOLDERS = [
	`${STAGE.APPELLANTCASE}/${DOCTYPE.APPELLANTSTATEMENT}`,
	`${STAGE.APPELLANTCASE}/${DOCTYPE.ORIGINALAPPLICATIONFORM}`,
	`${STAGE.APPELLANTCASE}/${DOCTYPE.APPLICATIONDECISION}`,
	`${STAGE.APPELLANTCASE}/${DOCTYPE.CHANGEDDESCRIPTION}`,
	`${STAGE.APPELLANTCASE}/${DOCTYPE.APPELLANTCASEWITHDRAWAL}`,
	`${STAGE.APPELLANTCASE}/${DOCTYPE.APPELLANTCASECORRESPONDENCE}`,
	`${STAGE.LPAQUESTIONNAIRE}/${DOCTYPE.WHONOTIFIED}`,
	`${STAGE.LPAQUESTIONNAIRE}/${DOCTYPE.CONSERVATIONMAP}`,
	`${STAGE.LPAQUESTIONNAIRE}/${DOCTYPE.OTHERPARTYREPS}`,
	`${STAGE.LPAQUESTIONNAIRE}/${DOCTYPE.PLANNINGOFFICERREPORT}`,
	`${STAGE.LPAQUESTIONNAIRE}/${DOCTYPE.LPACASECORRESPONDENCE}`,
	`${STAGE.COSTS}/appellant`,
	`${STAGE.COSTS}/lpa`,
	`${STAGE.COSTS}/decision`,
	// `${STAGE.COSTS}/${DOCTYPE.APPELLANTCOSTAPPLICATION}`,
	// `${STAGE.COSTS}/${DOCTYPE.APPELLANTCOSTWITHDRAWAL}`,
	// `${STAGE.COSTS}/${DOCTYPE.APPELLANTCOSTCORRESPONDENCE}`,
	// `${STAGE.COSTS}/${DOCTYPE.LPACOSTAPPLICATION}`,
	// `${STAGE.COSTS}/${DOCTYPE.LPACOSTWITHDRAWAL}`,
	// `${STAGE.COSTS}/${DOCTYPE.LPACOSTCORRESPONDENCE}`,
	// `${STAGE.COSTS}/${DOCTYPE.COSTDECISIONLETTER}`,
	`${STAGE.INTERNAL}/${DOCTYPE.CROSSTEAMCORRESPONDENCE}`,
	`${STAGE.INTERNAL}/${DOCTYPE.INSPECTORCORRESPONDENCE}`,
	`${STAGE.APPEALDECISION}/${DOCTYPE.CASEDECISIONLETTER}`
];
