BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Hearing] ALTER COLUMN [hearingStartTime] DATETIME2 NULL;
ALTER TABLE [dbo].[Hearing] ALTER COLUMN [estimatedDays] DECIMAL(32,16) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
