parameters:
  - name: Environment
    type: string
    default: 'dev'
    values: ['dev', 'test', 'staging']

  - name: RunParallel
    type: boolean
    default: true

variables:
  - name: APP
    value: 'appeals'
  - group: e2e-${{ parameters.Environment }}

pr: none
trigger: none

schedules:
  - cron: "0 2 * * 1-5"
    displayName: Weekday test run
    branches:
      include: [main]
    always: true

jobs:
  - job: Run_Cypress_Tests_For_Appeals
    timeoutInMinutes: 180
    pool: pins-odt-agent-pool-tests

    strategy:
      ${{ if eq(parameters.RunParallel, true) }}:
        matrix:
          group1:
            SPEC: >-
              issueDecision.spec.js,
              hearing.spec.js,
              reviewAppellantCase.spec.js,
              inquiry.spec.js,
              manuallyAddRepresentation.spec.js,
              part1.spec.js,
              personalList.spec.js,
              endToEndEnforcement.spec.js
          group2:
            SPEC: >-
              relatedAppeals.spec.js,
              manageCorrespondence.spec.js,
              manageDocsAppellant.spec.js,
              manageDocsLpa.spec.js,
              nationalListSearch.spec.js,
              reviewLpaq.spec.js,
              s78ChangeTimetable.spec.js,
              scheduleSiteVisit.spec.js,
              startCase.spec.js,
              unrelateAppeals.spec.js,
              updateLpaqDueDate.spec.js,
              addCostDecisionRedacted.spec.js,
              cancelAppeal.spec.js,
              captureNetResidence.spec.js,
              changeAppealProcedureType.spec.js,
              changeAppealType.spec.js,
              rule6Party.spec.js
          group3:
            SPEC: >-
              addCorrespondence.spec.js,
              appellantCase.spec.js,
              assignUserToCase.spec.js,
              caseHistory.spec.js,
              caseNotes.spec.js,
              changeContact.spec.js,
              changeSiteVisit.spec.js,
              changeStartDate.spec.js,
              globalValidation.spec.js,
              linkAppeals.spec.js,
              lpaStatement.spec.js,
              manageDocsSupporting.spec.js,
              endToEndAdvert.spec.js,
              endToEndS20.spec.js,
              endToEndS78.spec.js,
              updateDecisionLetter.spec.js

      #  SINGLE AGENT RUN (manual toggle)
      ${{ if eq(parameters.RunParallel, false) }}:
        matrix:
          single:
            SPEC: '**/*.spec.js'

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "22.x"
        displayName: "Install Node.js"
        
      - task: ShellScript@2
        inputs:
          scriptPath: 'appeals/e2e/install-chromium.sh'
        displayName: 'Install Chromium'
        condition: eq(variables['agent.os'], 'Linux')

      - task: Npm@1
        inputs:
          command: "install"
          workingDir: $(System.DefaultWorkingDirectory)/appeals/e2e
        displayName: "Install Dependencies"

      - script: |
          CLEAN_SPEC=$(echo "$(SPEC)" | tr -d ' \n' | sed 's/,/,cypress\/e2e\/back-office-appeals\//g')
          CLEAN_SPEC="cypress/e2e/back-office-appeals/$CLEAN_SPEC"
          echo "Running: $CLEAN_SPEC"
          npx cypress run --spec "$CLEAN_SPEC"
        workingDirectory: $(System.DefaultWorkingDirectory)/appeals/e2e        
        env:
          TZ: 'Europe/London'
          BASE_URL: $(APPEALS_BASE_URL)
          CASE_TEAM_EMAIL: $(CASE_TEAM_APPEALS_EMAIL)
          CASE_ADMIN_EMAIL: $(CASE_ADMIN_APPEALS_EMAIL)
          INSPECTOR_EMAIL: $(INSPECTOR_APPEALS_EMAIL)
          VALIDATION_OFFICER_EMAIL: $(VALIDATION_OFFICER_EMAIL)
          USER_PASSWORD: $(USER_PASSWORD)
          HAPPY_PATH_EMAIL: $(HAPPY_PATH_EMAIL)
        displayName: "Run Cypress Tests"

      - task: PublishBuildArtifacts@1
        condition: failed()
        inputs:
          pathToPublish: 'appeals/e2e/cypress/screenshots'
          artifactName: 'FailedTests'
        displayName: "Publish Failed Tests Artifacts"
