version: '3.7'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: db
        environment:
            - 'ACCEPT_EULA=Y'
            - 'MSSQL_SA_PASSWORD=SqlServer01'
        ports:
            - 1433:1433
    api:
        container_name: api
        build:
            context: .
            dockerfile: appeals/api/Dockerfile
            args:
                GIT_SHA: ${GIT_SHA}
        environment:
            - 'NODE_ENV=test'
            - 'DATABASE_URL=sqlserver://db:1433;database=pins_development;user=sa;password=SqlServer01;trustServerCertificate=true'
        ports:
            - 3000:3000
    web:
        container_name: web
        build:
            context: .
            dockerfile: appeals/web/Dockerfile
            args:
                GIT_SHA: ${GIT_SHA}
        environment:
            - 'NODE_ENV=test'
            - 'AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}'
            - 'AUTH_CLIENT_ID=${AUTH_CLIENT_ID}'
            - 'APP_HOSTNAME=api:8080'
            - 'API_HOST=http://api:3000'
            - 'AUTH_DISABLED=false'
            - 'SESSION_SECRET=dummy-secret'
            - 'AZURE_TENANT_ID=${AZURE_TENANT_ID}'
            - 'APPEALS_CASE_OFFICER_GROUP_ID=cc4133e5-2319-4762-8a7b-33413701210a'
            - 'APPEALS_INSPECTOR_GROUP_ID=0724c372-098d-4eef-acfb-bc85cd483dd1'
            - 'APPEALS_LEGAL_TEAM_GROUP_ID=369caed5-fe22-445e-8cdc-8b2f6746afc7'
            - 'APPEALS_CS_TEAM_GROUP_ID=455cbf03-f92f-4357-8daa-9f513b21fb73'
            - 'APPEALS_PADS_GROUP_ID=5afda392-73c5-4c18-a76f-7e3b1933813c'
            - 'APPEALS_READERS_GROUP_ID=60acabaa-6ac9-4462-828a-b79adc3d802c'
            - 'HTTPS_ENABLED=true'
            - 'HTTPS_PORT=8080'
            - 'SSL_CERT_FILE=../../certificate.pem'
            - 'SSL_KEY_FILE=../../certificate-key.pem'
        ports:
            - 8080:8080

