version: '3.7'
services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: db
        environment:
            - 'ACCEPT_EULA=Y'
            - 'MSSQL_SA_PASSWORD=SqlServer01'
        ports:
            - 1433:1433
        healthcheck:
            test: [ "CMD-SHELL", "sqlcmd -S localhost -U sa -P SqlServer01 -Q 'SELECT 1'" ]
            interval: 10s
            timeout: 5s
            retries: 10
    db-init:
        container_name: db-init
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_ENV: test
                DATABASE_URL: sqlserver://db:1433;database=pins_development;user=sa;password=SqlServer01;trustServerCertificate=true
        depends_on:
            db:
                condition: service_healthy
    api:
        depends_on:
            db-init:
                condition: service_completed_successfully
        container_name: api
        build:
            context: .
            dockerfile: appeals/api/Dockerfile
            args:
                GIT_SHA: ${GIT_SHA}
        environment:
            - 'NODE_ENV=test'
            - 'DATABASE_URL=sqlserver://db:1433;database=pins_development;user=sa;password=SqlServer01;trustServerCertificate=true'
        ports:
            - 3000:3000
    web:
        container_name: web
        build:
            context: .
            dockerfile: appeals/web/Dockerfile
            args:
                GIT_SHA: ${GIT_SHA}
        environment:
            - 'NODE_ENV=test'
            - 'AUTH_CLIENT_SECRET=${AUTH_CLIENT_SECRET}'
            - 'AUTH_CLIENT_ID=${AUTH_CLIENT_ID}'
            - 'APP_HOSTNAME=api:8080'
            - 'API_HOST=http://api:3000'
            - 'AUTH_DISABLED=false'
            - 'SESSION_SECRET=dummy-secret'
        ports:
            - 8080:8080

