import { createMachine } from 'xstate';
import { APPEAL_CASE_STATUS } from 'pins-data-model';

import {
	APPEAL_TYPE_SHORTHAND_HAS,
	STATE_TYPE_FINAL,
	VALIDATION_OUTCOME_COMPLETE,
	VALIDATION_OUTCOME_INCOMPLETE,
	VALIDATION_OUTCOME_INVALID,
	VALIDATION_OUTCOME_VALID
} from '../../endpoints/constants.js';

/**
 * @param {string} currentState
 */
const stateMachine = (currentState) =>
	createMachine({
		id: APPEAL_TYPE_SHORTHAND_HAS,
		initial: currentState || APPEAL_CASE_STATUS.ASSIGN_CASE_OFFICER,
		states: {
			[APPEAL_CASE_STATUS.ASSIGN_CASE_OFFICER]: {
				on: {
					[APPEAL_CASE_STATUS.VALIDATION]: { target: APPEAL_CASE_STATUS.VALIDATION },
					[APPEAL_CASE_STATUS.CLOSED]: { target: APPEAL_CASE_STATUS.CLOSED },
					[APPEAL_CASE_STATUS.AWAITING_TRANSFER]: {
						target: APPEAL_CASE_STATUS.AWAITING_TRANSFER
					},
					[APPEAL_CASE_STATUS.WITHDRAWN]: {
						target: APPEAL_CASE_STATUS.WITHDRAWN
					}
				}
			},
			[APPEAL_CASE_STATUS.VALIDATION]: {
				on: {
					[VALIDATION_OUTCOME_VALID]: { target: APPEAL_CASE_STATUS.READY_TO_START },
					[VALIDATION_OUTCOME_INVALID]: { target: APPEAL_CASE_STATUS.INVALID },
					[VALIDATION_OUTCOME_INCOMPLETE]: undefined,
					[APPEAL_CASE_STATUS.CLOSED]: { target: APPEAL_CASE_STATUS.CLOSED },
					[APPEAL_CASE_STATUS.AWAITING_TRANSFER]: {
						target: APPEAL_CASE_STATUS.AWAITING_TRANSFER
					},
					[APPEAL_CASE_STATUS.WITHDRAWN]: {
						target: APPEAL_CASE_STATUS.WITHDRAWN
					}
				}
			},
			[APPEAL_CASE_STATUS.READY_TO_START]: {
				on: {
					[APPEAL_CASE_STATUS.LPA_QUESTIONNAIRE]: {
						target: APPEAL_CASE_STATUS.LPA_QUESTIONNAIRE
					},
					[APPEAL_CASE_STATUS.CLOSED]: { target: APPEAL_CASE_STATUS.CLOSED },
					[APPEAL_CASE_STATUS.AWAITING_TRANSFER]: {
						target: APPEAL_CASE_STATUS.AWAITING_TRANSFER
					},
					[APPEAL_CASE_STATUS.WITHDRAWN]: {
						target: APPEAL_CASE_STATUS.WITHDRAWN
					}
				}
			},
			[APPEAL_CASE_STATUS.LPA_QUESTIONNAIRE]: {
				on: {
					[VALIDATION_OUTCOME_COMPLETE]: { target: APPEAL_CASE_STATUS.EVENT },
					[VALIDATION_OUTCOME_INCOMPLETE]: undefined,
					[APPEAL_CASE_STATUS.CLOSED]: { target: APPEAL_CASE_STATUS.CLOSED },
					[APPEAL_CASE_STATUS.AWAITING_TRANSFER]: {
						target: APPEAL_CASE_STATUS.AWAITING_TRANSFER
					},
					[APPEAL_CASE_STATUS.WITHDRAWN]: {
						target: APPEAL_CASE_STATUS.WITHDRAWN
					}
				}
			},
			[APPEAL_CASE_STATUS.EVENT]: {
				on: {
					[VALIDATION_OUTCOME_COMPLETE]: { target: APPEAL_CASE_STATUS.AWAITING_EVENT },
					[VALIDATION_OUTCOME_INCOMPLETE]: { target: undefined },
					[APPEAL_CASE_STATUS.CLOSED]: { target: APPEAL_CASE_STATUS.CLOSED },
					[APPEAL_CASE_STATUS.AWAITING_TRANSFER]: {
						target: APPEAL_CASE_STATUS.AWAITING_TRANSFER
					},
					[APPEAL_CASE_STATUS.WITHDRAWN]: {
						target: APPEAL_CASE_STATUS.WITHDRAWN
					}
				}
			},
			[APPEAL_CASE_STATUS.AWAITING_EVENT]: {
				on: {
					[VALIDATION_OUTCOME_COMPLETE]: { target: APPEAL_CASE_STATUS.ISSUE_DETERMINATION },
					[VALIDATION_OUTCOME_INCOMPLETE]: { target: undefined },
					[APPEAL_CASE_STATUS.CLOSED]: { target: APPEAL_CASE_STATUS.CLOSED },
					[APPEAL_CASE_STATUS.AWAITING_TRANSFER]: {
						target: APPEAL_CASE_STATUS.AWAITING_TRANSFER
					},
					[APPEAL_CASE_STATUS.WITHDRAWN]: {
						target: APPEAL_CASE_STATUS.WITHDRAWN
					}
				}
			},
			[APPEAL_CASE_STATUS.ISSUE_DETERMINATION]: {
				on: {
					[APPEAL_CASE_STATUS.COMPLETE]: { target: APPEAL_CASE_STATUS.COMPLETE },
					[APPEAL_CASE_STATUS.CLOSED]: { target: APPEAL_CASE_STATUS.CLOSED },
					[APPEAL_CASE_STATUS.AWAITING_TRANSFER]: {
						target: APPEAL_CASE_STATUS.AWAITING_TRANSFER
					},
					[APPEAL_CASE_STATUS.INVALID]: { target: APPEAL_CASE_STATUS.INVALID },
					[APPEAL_CASE_STATUS.WITHDRAWN]: {
						target: APPEAL_CASE_STATUS.WITHDRAWN
					}
				}
			},
			[APPEAL_CASE_STATUS.AWAITING_TRANSFER]: {
				on: {
					[APPEAL_CASE_STATUS.TRANSFERRED]: { target: APPEAL_CASE_STATUS.TRANSFERRED }
				}
			},
			[APPEAL_CASE_STATUS.INVALID]: {
				type: STATE_TYPE_FINAL
			},
			[APPEAL_CASE_STATUS.TRANSFERRED]: {
				type: STATE_TYPE_FINAL
			},
			[APPEAL_CASE_STATUS.CLOSED]: {
				type: STATE_TYPE_FINAL
			},
			[APPEAL_CASE_STATUS.WITHDRAWN]: {
				type: STATE_TYPE_FINAL
			},
			[APPEAL_CASE_STATUS.COMPLETE]: {
				type: STATE_TYPE_FINAL
			}
		}
	});

export default stateMachine;
