export const STATUSES = Object.freeze({
	ASSIGN_CASE_OFFICER: 'ASSIGN_CASE_OFFICER',
	VALIDATION: 'VALIDATION',
	READY_TO_START: 'READY_TO_START',
	LPA_QUESTIONNAIRE: 'LPA_QUESTIONNAIRE',
	STATEMENTS: 'STATEMENTS',
	FINAL_COMMENTS: 'FINAL_COMMENTS',
	EVENT_READY_TO_SETUP: 'EVENT_READY_TO_SETUP',
	AWAITING_EVENT: 'AWAITING_EVENT',
	ISSUE_DECISION: 'ISSUE_DECISION',
	COMPLETE: 'COMPLETE'
});

export const FLOWS = Object.freeze({
	HAS: [
		STATUSES.ASSIGN_CASE_OFFICER,
		STATUSES.VALIDATION,
		STATUSES.READY_TO_START,
		STATUSES.LPA_QUESTIONNAIRE,
		STATUSES.EVENT_READY_TO_SETUP,
		STATUSES.AWAITING_EVENT,
		STATUSES.ISSUE_DECISION,
		STATUSES.COMPLETE
	],
	S78: [
		STATUSES.ASSIGN_CASE_OFFICER,
		STATUSES.VALIDATION,
		STATUSES.READY_TO_START,
		STATUSES.LPA_QUESTIONNAIRE,
		STATUSES.STATEMENTS,
		STATUSES.FINAL_COMMENTS,
		STATUSES.EVENT_READY_TO_SETUP,
		STATUSES.AWAITING_EVENT,
		STATUSES.ISSUE_DECISION,
		STATUSES.COMPLETE
	],
	S20: [
		STATUSES.ASSIGN_CASE_OFFICER,
		STATUSES.VALIDATION,
		STATUSES.READY_TO_START,
		STATUSES.LPA_QUESTIONNAIRE,
		STATUSES.STATEMENTS,
		STATUSES.FINAL_COMMENTS,
		STATUSES.EVENT_READY_TO_SETUP,
		STATUSES.AWAITING_EVENT,
		STATUSES.ISSUE_DECISION,
		STATUSES.COMPLETE
	]
});
