export const STATUSES = Object.freeze({
	ASSIGN_CASE_OFFICER: 'ASSIGN_CASE_OFFICER',
	VALIDATION: 'VALIDATION',
	READY_TO_START: 'READY_TO_START',
	LPA_QUESTIONNAIRE: 'LPA_QUESTIONNAIRE',
	STATEMENTS: 'STATEMENTS',
	FINAL_COMMENTS: 'FINAL_COMMENTS',
	EVIDENCE: 'EVIDENCE',
	EVENT_READY_TO_SETUP: 'EVENT_READY_TO_SETUP',
	AWAITING_EVENT: 'AWAITING_EVENT',
	ISSUE_DECISION: 'ISSUE_DECISION',
	COMPLETE: 'COMPLETE'
});

export const FLOWS = Object.freeze({
	HAS: [
		STATUSES.ASSIGN_CASE_OFFICER,
		STATUSES.VALIDATION,
		STATUSES.READY_TO_START,
		STATUSES.LPA_QUESTIONNAIRE,
		STATUSES.EVENT_READY_TO_SETUP,
		STATUSES.AWAITING_EVENT,
		STATUSES.ISSUE_DECISION,
		STATUSES.COMPLETE
	],
	S78: [
		STATUSES.ASSIGN_CASE_OFFICER,
		STATUSES.VALIDATION,
		STATUSES.READY_TO_START,
		STATUSES.LPA_QUESTIONNAIRE,
		STATUSES.STATEMENTS,
		STATUSES.FINAL_COMMENTS,
		STATUSES.EVIDENCE,
		STATUSES.EVENT_READY_TO_SETUP,
		STATUSES.AWAITING_EVENT,
		STATUSES.ISSUE_DECISION,
		STATUSES.COMPLETE
	],
	S20: [
		STATUSES.ASSIGN_CASE_OFFICER,
		STATUSES.VALIDATION,
		STATUSES.READY_TO_START,
		STATUSES.LPA_QUESTIONNAIRE,
		STATUSES.STATEMENTS,
		STATUSES.FINAL_COMMENTS,
		STATUSES.EVENT_READY_TO_SETUP,
		STATUSES.AWAITING_EVENT,
		STATUSES.ISSUE_DECISION,
		STATUSES.COMPLETE
	],
	CAS_PLANNING: [
		STATUSES.ASSIGN_CASE_OFFICER,
		STATUSES.VALIDATION,
		STATUSES.READY_TO_START,
		STATUSES.LPA_QUESTIONNAIRE,
		STATUSES.EVENT_READY_TO_SETUP,
		STATUSES.AWAITING_EVENT,
		STATUSES.ISSUE_DECISION,
		STATUSES.COMPLETE
	],
	CAS_ADVERT: [
		STATUSES.ASSIGN_CASE_OFFICER,
		STATUSES.VALIDATION,
		STATUSES.READY_TO_START,
		STATUSES.LPA_QUESTIONNAIRE,
		STATUSES.EVENT_READY_TO_SETUP,
		STATUSES.AWAITING_EVENT,
		STATUSES.ISSUE_DECISION,
		STATUSES.COMPLETE
	],
	ADVERT: [
		STATUSES.ASSIGN_CASE_OFFICER,
		STATUSES.VALIDATION,
		STATUSES.READY_TO_START,
		STATUSES.LPA_QUESTIONNAIRE,
		STATUSES.STATEMENTS,
		STATUSES.FINAL_COMMENTS,
		STATUSES.EVIDENCE,
		STATUSES.EVENT_READY_TO_SETUP,
		STATUSES.AWAITING_EVENT,
		STATUSES.ISSUE_DECISION,
		STATUSES.COMPLETE
	]
});

//For Autocomplete
/**
 * @typedef {(
 *  'ASSIGN_CASE_OFFICER' |
 *  'VALIDATION' |
 *  'READY_TO_START' |
 *  'LPA_QUESTIONNAIRE' |
 *  'STATEMENTS' |
 *  'FINAL_COMMENTS' |
 *  'EVIDENCE' |
 *  'EVENT_READY_TO_SETUP' |
 *  'AWAITING_EVENT' |
 *  'ISSUE_DECISION' |
 *  'COMPLETE'
 * )} Status
 *
 * @typedef {(
 *  'HAS' |
 *  'S78' |
 *  'S20' |
 *  'CAS_PLANNING' |
 *  'CAS_ADVERT' |
 *  'ADVERT'
 * )} AppealType
 *
 * @typedef {(
 *  'WRITTEN' |
 *  'HEARING' |
 *  'INQUIRY'
 * )} ProcedureType
 */
