trigger: none

pr: none

resources:
  pipelines:
    - pipeline: terraform-ci
      source: Infrastructure PR
      trigger:
        branches:
          include:
            - main
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.15.2

extends:
  template: pipelines/terraform_plan_apply.yml@templates
  parameters:
    environments:
      - name: Dev
      - name: Test
        dependsOn:
          - Dev
      - name: Prod
        dependsOn:
          - Test
    serviceConnectionPrefix: Azure DevOps Pipelines - Appeals Back Office - Infrastructure
    storageAccountName: pinssttfstateuksappealbo
    resourceGroupName: pins-rg-shared-terraform-uks
    containerPrefix: terraform-state-appeals-back-office-
    workingDirectory: $(Build.Repository.LocalPath)/infrastructure
    environmentVarFilePath: $(Build.Repository.LocalPath)/infrastructure/environments
