trigger: none

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - infrastructure

resources:
  repositories:
    - repository: templates
      type: github
      endpoint: Planning-Inspectorate
      name: Planning-Inspectorate/common-pipeline-templates
      ref: refs/tags/release/3.24.2

extends:
  template: stages/wrapper_ci.yml@templates
  parameters:
    gitFetchDepth: 0
    globalVariables:
      - template: azure-pipelines-variables.yml@self
    validationJobs:
      - name: Check Commits
        steps:
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm ci
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm run commitlint
      - name: Run cypress e2e tests
        dependantOn: Check PR labels
        condition: eq(variables['Build.Reason'], 'PullRequest')
        steps:
          - task: ShellScript@2
            inputs:
                scriptPath: 'appeals/e2e/install-chromium.sh'
            displayName: 'Install Chromium'
            condition: eq(variables['agent.os'], 'Linux')
          - task: DockerInstaller@0
            inputs:
              dockerVersion: '17.09.0-ce'
          - script:
              docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=SqlServer01" -p 1433:1433 --name pins-sql-server -d mcr.microsoft.com/mssql/server:2022-latest
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: npm ci
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: DATABASE_URL="sqlserver://127.0.0.1:1433;database=pins_development;user=sa;password=SqlServer01;trustServerCertificate=true" npm --prefix ./appeals/api run db:migrate
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: |
                  NODE_ENV=test npm run api &
          - template: ../steps/node_script.yml
            parameters:
              nodeVersion: 22
              script: |
                  NODE_ENV=test npm run web &
          - template: ../steps/node_script.yml
            parameters:
                nodeVersion: 22
                script: npx cypress run --spec "cypress/e2e/back-office-appeals/**/*.spec.js"

